### ISSUE TITLE
Not receiving Chrome notifications on Android device

### ISSUE THREAD

**Issue by kelvinwatson** [google/physical-web#905]
I recently purchased iBKS105 beacons from accent systems (one of the companies recommended by the Google Beacon platform https://developers.google.com/beacons/eddystone#beacon_manufacturers). I configured the beacon using the instructions provided by accent systems to emit a URL (https://reddit.com), which I verified on http://verify.physical-web.org. After following the instructions here (https://google.github.io/physical-web/try-physical-web), I am unable to receive any Chrome notifications.

I am, however, able to detect the beacon and receive notifications successfully via Google Nearby Notifications and the Physical Web app (screenshot below). Note that I am also able to get Chrome notifications for my beacon successfully on iOS (iPhone 7).

![screenshot_20170429-151941](https://cloud.githubusercontent.com/assets/11381360/25558189/63b4dd50-2cef-11e7-80ad-ed41734546da.png)

Here is what I have tried so far that has not worked:
- Enabling Physical Web in Chrome --> Settings --> Privacy --> Physical Web (I also saw instructions to turn "Do not track" to on but doing that did not have any effect)
- Setting the phone to sleep, then waking it up

About the Android device I'm using:
- Nexus 5x running Android version 7.1.2
- Chrome version 57.0.2987.132

Would someone be able to point out what I'm doing wrong and why I cannot receive Chrome physical-web notifications? Any help would be appreciated.

**Comment by ferencbrachmann** [comment]
If you're getting Nearby notifications than Chrome does show (duplicate) notifications.
Note: Chrome for iOS and Andorid Beta currently show PW autocomplete suggestions inside the browser.

**Comment by kelvinwatson** [comment]
@ferencbrachmann I only see the duplicate when I have the [Physical Web](https://play.google.com/store/apps/details?id=physical_web.org.physicalweb&hl=en) application installed. When I uninstall Physical Web, I get zero notifications.

**Comment by ferencbrachmann** [comment]
Now I understand. Please go to Chrome Settings / Nearby and conduct a scan.

@scottjenson any comments?

**Comment by kelvinwatson** [comment]
@ferencbrachmann I get an empty screen when I conduct a scan.
![screenshot_20170429-153355](https://cloud.githubusercontent.com/assets/11381360/25558280/574a60ce-2cf1-11e7-9ebf-f62ca7e9e0f6.png)

**Comment by ferencbrachmann** [comment]
Sorry, I ment Google Settings / Nearby.

**Comment by ferencbrachmann** [comment]
With the current Chrome release you're supposed to get this. Download Chrome beta for this page and for Chrome autocomplete suggestions to work!

**Comment by kelvinwatson** [comment]
@ferencbrachmann Correction, I do see the beacon on both chrome://physical-web after conducting the scan, and Google Settings/Nearby.

However, I am still not getting any Chrome notifications.

**Comment by kelvinwatson** [comment]
@ferencbrachmann I am not sure what you mean by Chrome autocomplete suggestions. I am trying to get Chrome notifications, but I am currently not reeceiving any.

**Comment by ferencbrachmann** [comment]
You should be getting suggestions like these:
![chrome_ios_iphone](https://cloud.githubusercontent.com/assets/20400452/25558426/a6ef08e8-2d26-11e7-875a-f904001bbd52.png)

**Comment by kelvinwatson** [comment]
@ferencbrachmann The screenshot you posted seems to be iOS, but I am trying to get Chrome notifications on Android.

**Comment by ferencbrachmann** [comment]
You'll get the same thing on Chrome for Android Beta (without the PW logo for now)

**Comment by luciofr** [comment]
@ferencbrachmann I have the same problem with some versions of Android, Chrome does not manage more Nearby, who does this after some updates is Google Play Services, in other versions of Android you manage Nearby by Google Config ----> Nearby , But it does not become a standard which brings many problems. What I do not understand is the following, for which reason the Android Native Nearby, does not work as the Physiacl Web Application, that is 100%, including whether my Beacon is working using the Physical Web application or via Chrome notifications in one IPhone, so far no reply. @scottjenson @mmocny any comments?

**Comment by ferencbrachmann** [comment]
Nearby does filter some page content if it gets swiped away too many times. You may have ran into this. Please also try the URL validator: https://beaufortfrancois.github.io/sandbox/physical-web/url-validator/

**Comment by luciofr** [comment]
@ferencbrachmann but the Physical Web Aplication never fails, why does the Nearby Native Android not use the same mechanism? Via iOS the same thing, notifications of Chrome on any iPhone, always work, there is some problem in Nearby native Android, I hope it is corrected as soon as possible, as it is difficult to have a technology that works intermittently . All my URLs passed through the validator successfully( Example: https://tagzone.com.br/?18e8a ). See the screens below, the print was almost at the same time.
![whatsapp image 2017-05-01 at 17 31 41 1](https://cloud.githubusercontent.com/assets/27795008/25593819/a7588358-2e94-11e7-9134-158a5d13cdeb.jpeg)
![whatsapp image 2017-05-01 at 17 31 41](https://cloud.githubusercontent.com/assets/27795008/25593818/a757dc00-2e94-11e7-8314-9606e9b6ab1c.jpeg)
![whatsapp image 2017-05-01 at 17 33 54](https://cloud.githubusercontent.com/assets/27795008/25593827/afff9c26-2e94-11e7-9637-d77b2cae6f3b.jpeg)

**Comment by sime** [comment]
I have come back to experimenting with Beacons after having great success around 12 months ago. Currently I am in the same situation as @luciofr. Nearby beacons only appear with the Physical Web application on Android.

**Comment by ferencbrachmann** [comment]
Please check your URL here: verify.physical-web.org there were quite a few changes in the last 12 months.

**Comment by sime** [comment]
@ferencbrachmann Thanks, I saw this mentioned a number of times and have checked against it already.
Still not discoverable on Nearby/Android. Trying with a real beacon and broadcasting from OS X using the `eddystone-beacon` Node.js module.

**Comment by sime** [comment]
To note: testing on Android 5 and 6.

**Comment by ferencbrachmann** [comment]
Can you share the URL/short URL? There is some chance this is a bug (or maybe a feature of the content filter of the PW service that does not display URLs that have been swiped away too many times) I have not yet reported but do experience it with a certain URL.

Also cross check your URL by going into Google Settings / Nearby. You may still see it in the list but it does not fire a notification.

**Comment by sime** [comment]
@ferencbrachmann I've tried many URLs, including google.com. For domains I control: https://village.pe and https://sime.net.au

Nearby doesn't show a list at all.

**Comment by ferencbrachmann** [comment]
Hmm. I wouldn't say this is unheard of, but it still is pretty rare. @mmocny do you have any ideas what it could be?

**Comment by mmocny** [comment]
Based on your symptoms:
1. Many different URL do not show at all in the Nearby list
2. They show in the PW app on the same device, at the same time

.. I would conclude that there is an issue with Nearby scanning.

You could help by taking a bug report, by following these instructions:
1. Enable Developer Mode for the android device.
2. Turn on "debug mode" for Nearby (Settings > Google > Nearby > Gear icon > "Include debug results")
3.  Use Android "Take bug report" feature.

You can find instructions for steps 1 and 3 [here](https://developer.android.com/studio/debug/bug-report.html).

Once you have a bug report, may you email it to mmocny@google.com and jfarfel@google.com please?

**Comment by sime** [comment]
I believe the problem is unique to Nexus 4. I have tested on two separate devices (Android 5 and 6). Other phones don't have this problem.

**Comment by mmocny** [comment]
This helps.  I do not have that device myself, but AFAIK that was one of the first android devices to support BLE 4.0

**Comment by sime** [comment]
It worked great 12 months ago, prior to the "Nearby" concept.

**Comment by tagpoint** [comment]
@sime, I already have my URLs resolved, Neraby Nativo gets 100%. In addition to a double jump in our URLs, which we have corrected, for just one jump, we also had problems in the configuration of our Hardware, since our Beacons work simultaneously iBeacon and Eddystone, after the correct corrections everything remained 100% in the Near Native of Android. One attitude that we understand was fundamental to the resolution, is that we do not change the URL of Beacon, always the same, so we do not lose positioning in Google Servers.
